### PR TITLE
Fix a small typo in the help text

### LINKED ISSUE #4: Small typo in the help text
I noticed a small typo in the maas-anvil --help text. Here is the help text from commands.py:

```
To get started with a single node, all-in-one MAAS installation, start
with by initializing the local node. Once the local node has been initialized,
run the bootstrap process to get a live MAAS deployment.
```
The typo is in the first sentence "To get started with a single node, all-in-one MAAS installation, start with **by** initializing the local node."

I think the word **by** needs to be removed. It's a small change for a first issue. I will submit a PR to fix the typo.

### PR DESCRIPTION
**Pull request by jadonn**
Closes #4. There is a small typo in the help text. This change removes an extra word.

### CODE REVIEW

**Comment by skatsaounis** [comment]
`/canonical/self-hosted-runners/run-workflows 1d95d6e015b6e36ac829054e6c47a1b17a62c265` accepted

**Review by skatsaounis — APPROVED** [review]
LGTM +1

**Comment by skatsaounis** [comment]
@jadonn it seems that your commit is not signed. Could you please update it and force push your branch? Thank you :slightly_smiling_face:

**Comment by jadonn** [comment]
Sorry about that @skatsaounis! I have updated the commit with a signature and force pushed my branch. Please let me know if you need me to do anything else. Thank you!

**Comment by skatsaounis** [comment]
:rocket:

**Pull request merged**
